version: '3.9'

services:

    https:
      image: nginx:latest
      ports:
        - "443:443"
      volumes:
        - ./html:/usr/share/nginx/html:ro
        - ./nginx:/etc/nginx
        - ./cert:/cert

    http:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./html1:/usr/share/nginx/html


      